In [1]:
import numpy as np

In [2]:
height = [1.23,3.26,4.1,2.2]
np_arr = np.array(height)

In [3]:
np_arr

array([1.23, 3.26, 4.1 , 2.2 ])

In [4]:
weight = [42.03,56.2,72.0,65.454]
np_w = np.array(weight)
np_w

array([42.03 , 56.2  , 72.   , 65.454])

In [5]:
bmi = np_w/np_arr ** 2
bmi

array([27.78108269,  5.28811773,  4.28316478, 13.52355372])

In [6]:
bmi[3]

13.52355371900826

In [7]:
bmi > 20

array([ True, False, False, False])

In [8]:
bmi[bmi>20]

array([27.78108269])

In [9]:
np_baseball = np.array([20,30,50,60])
print(type(np_baseball))

<class 'numpy.ndarray'>


In [10]:
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)
