In [1]:
import numpy as np

In [2]:
arr = np.array([2, 4, 6, 8, 10])

c = arr.copy()

print("id of arr", id(arr))
print("id of c", id(c))

arr[0] = 24

print("Original array- ", arr)
print("Copy- ", c)

id of arr 138213535560592
id of c 138213535561648
Original array-  [24  4  6  8 10]
Copy-  [ 2  4  6  8 10]


In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)

arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)

arr = np.append(arr1, arr2)
print('Array after appending : ', arr)


First array is :  [1 2 3]
Second array is :  [4 5 6]
Array after appending :  [1 2 3 4 5 6]


In [4]:
import numpy as np

my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)

my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("After swapping arrays the last column and first column:")
print(my_array)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [5]:
import numpy as np

new_arr = np.array([[ 78,  23,  41,  66],
              [ 109,  167,  41,  28],
              [ 187, 22, 76, 88]])
b = new_arr.reshape(3, 2, 2)

print("Created 3D array:\n",b)
print("The dimension of the array:", b.ndim)

Created 3D array:
 [[[ 78  23]
  [ 41  66]]

 [[109 167]
  [ 41  28]]

 [[187  22]
  [ 76  88]]]
The dimension of the array: 3


In [6]:
import numpy as np

new_arr2 = np.array([[[178, 189, 567], [145, 239, 445], [197, 345, 678]],
                [[56, 78, 190], [46, 10, 11], [6, 2, 1]],
                [[45, 118, 203], [72, 119, 34], [87, 9, 5]]])

d= new_arr2[:2,1:,:2]
print("slicing array:\n",d)
print("The dimension of the array:", d.ndim)

slicing array:
 [[[145 239]
  [197 345]]

 [[ 46  10]
  [  6   2]]]
The dimension of the array: 3


In [7]:
import numpy as np

new_arr2 = np.array([[[13, 9],
        [161, 23]],

       [[128, 219],
        [109, 992]],

       [[42,  34],
        [ 128,  398]],

       [[236,  557],
        [645, 212]]])
b= np.reshape(new_arr2,(4,4))
print("Output array:\n",b)
print("The dimension of the array:", b.ndim)

Output array:
 [[ 13   9 161  23]
 [128 219 109 992]
 [ 42  34 128 398]
 [236 557 645 212]]
The dimension of the array: 2


In [8]:
import numpy as np

# Create a 2D array manually
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("The array is:\n", data)
print("Data type:", type(data))
print("Number of dimensions:", np.ndim(data))
print("Total elements:", data.size)
print("Shape (rows, columns):", data.shape)


The array is:
 [[1 2 3 4]
 [5 6 7 8]]
Data type: <class 'numpy.ndarray'>
Number of dimensions: 2
Total elements: 8
Shape (rows, columns): (2, 4)


In [9]:
# Access an element
element = data[1, 2]  # Row 1, Column 2 (value: 7)
print("Element at (1, 2):", element)

# Slice a row
row_slice = data[0, :]  # First row
print("First row:", row_slice)

# Slice a column
column_slice = data[:, 1]  # Second column
print("Second column:", column_slice)


Element at (1, 2): 7
First row: [1 2 3 4]
Second column: [2 6]


In [10]:
import numpy as np

# Create the arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Add the arrays element-wise
result = A + B

print("Array A:\n", A)
print("Array B:\n", B)
print("Sum of A and B:\n", result)


Array A:
 [[1 2 3]
 [4 5 6]]
Array B:
 [[ 7  8  9]
 [10 11 12]]
Sum of A and B:
 [[ 8 10 12]
 [14 16 18]]


In [11]:
import numpy as np

# Create two 2D arrays
x1 = np.array([[1, 2], [0, 5]])
x2 = np.array([[3, 1], [7, 1]])

# Multiply x1 and x2 element-wise
result = np.multiply(x1, x2)

print("Resultant output array:\n", result)


Resultant output array:
 [[3 2]
 [0 5]]
